[project]
name = "poki_koa"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "Ricardo Figueroa, Sarai Herrera, Sebastian Quinzacaras, Ricardo Loyola, Mauricio Escobar" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1",
]

[project.scripts]
poki_koa = "poki_koa:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
