# Generated by Django 6.1 on 2026-08-16 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Ej: Sofía García', max_length=200)),
                ('edad_meses', models.IntegerField(help_text='Edad en meses')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Ej: Dra. María López', max_length=150)),
                ('turno', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Ej: Cuna 01', max_length=20, unique=True)),
                ('ritmo_cardiaco', models.IntegerField(blank=True, help_text='Latidos por minuto (bpm)', null=True)),
                ('spo2', models.IntegerField(blank=True, help_text='Nivel de oxígeno (%)', null=True)),
                ('estado_sueno', models.CharField(choices=[('Dormido', 'Dormido'), ('Despierto', 'Despierto')], default='Despierto', max_length=20)),
                ('canula_ok', models.BooleanField(default=True, help_text='¿La cánula está funcionando bien?')),
                ('via_iv_activa', models.BooleanField(default=False, help_text='¿La vía intravenosa está activa?')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cunas.bebe')),
            ],
        ),
        migrations.AddField(
            model_name='bebe',
            name='medico_a_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cunas.medico'),
        ),
    ]
