# Generated by Django 6.1 on 2026-08-19 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bebe',
            options={'verbose_name': 'Bebé', 'verbose_name_plural': 'Bebés'},
        ),
        migrations.AlterModelOptions(
            name='cuna',
            options={'verbose_name': 'Cuna', 'verbose_name_plural': 'Cunas'},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AddField(
            model_name='bebe',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del bebé (no puede ser futura)', null=True),
        ),
        migrations.AddField(
            model_name='bebe',
            name='peso',
            field=models.FloatField(blank=True, help_text='Peso del bebé en kilogramos (debe ser mayor a 0)', null=True),
        ),
        migrations.AlterField(
            model_name='bebe',
            name='edad_meses',
            field=models.IntegerField(help_text='Edad del bebé expresada en meses'),
        ),
        migrations.AlterField(
            model_name='bebe',
            name='medico_a_cargo',
            field=models.ForeignKey(blank=True, help_text='Médico responsable del seguimiento de este bebé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='cunas.medico'),
        ),
        migrations.AlterField(
            model_name='cuna',
            name='canula_ok',
            field=models.BooleanField(default=True, help_text='True si la cánula de oxígeno está funcionando correctamente'),
        ),
        migrations.AlterField(
            model_name='cuna',
            name='estado_sueno',
            field=models.CharField(choices=[('Dormido', 'Dormido'), ('Despierto', 'Despierto')], default='Despierto', help_text='Estado de sueño detectado por el sensor', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuna',
            name='identificador',
            field=models.CharField(help_text="Identificador único de la cuna, ej: 'Cuna 01'", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cuna',
            name='paciente',
            field=models.OneToOneField(blank=True, help_text='Bebé actualmente asignado a esta cuna', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuna_asignada', to='cunas.bebe'),
        ),
        migrations.AlterField(
            model_name='cuna',
            name='ritmo_cardiaco',
            field=models.IntegerField(blank=True, help_text='Frecuencia cardíaca en latidos por minuto (bpm)', null=True),
        ),
        migrations.AlterField(
            model_name='cuna',
            name='spo2',
            field=models.IntegerField(blank=True, help_text='Saturación de oxígeno en sangre (%)', null=True),
        ),
        migrations.AlterField(
            model_name='cuna',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización de datos'),
        ),
        migrations.AlterField(
            model_name='cuna',
            name='via_iv_activa',
            field=models.BooleanField(default=False, help_text='True si la vía intravenosa está activa'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='turno',
            field=models.CharField(blank=True, help_text='Turno de trabajo del médico (ej: Mañana, Tarde, Noche)', max_length=50, null=True),
        ),
    ]
