# Generated by Django 6.1 on 2026-08-27 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunas', '0002_agregar_peso_fecha_nacimiento_bebe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuna',
            name='identificador',
            field=models.CharField(help_text="Identificador único de la cuna, ej: 'C01'", max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del medicamento (ej: Fenobarbital, Vitamina K)', max_length=150)),
                ('dosis', models.CharField(help_text='Cantidad y unidad de la dosis (ej: 5 mg/kg)', max_length=50)),
                ('via', models.CharField(choices=[('IV', 'Intravenosa (IV)'), ('IM', 'Intramuscular (IM)'), ('ET', 'Endotraqueal (ET)'), ('VO', 'Vía Oral (VO)')], help_text='Vía de administración del fármaco', max_length=2)),
                ('hora', models.TimeField(help_text='Hora programada o en la que se administró el medicamento')),
                ('estado', models.CharField(choices=[('Administrado', 'Administrado'), ('Pendiente', 'Pendiente')], default='Pendiente', help_text='Estado actual de la administración', max_length=20)),
                ('paciente', models.ForeignKey(help_text='Paciente al que se le administra el fármaco', on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='cunas.bebe')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
    ]
