# Generated by Django 6.1 on 2026-08-27 19:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunas', '0003_alter_cuna_identificador_medicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebe',
            name='diagnostico',
            field=models.TextField(blank=True, help_text='Diagnóstico médico principal o motivo de ingreso', null=True),
        ),
        migrations.AddField(
            model_name='bebe',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de ingreso del bebé a la unidad neonatal'),
        ),
        migrations.AddField(
            model_name='bebe',
            name='plan_cuidados',
            field=models.TextField(blank=True, help_text='Plan de cuidados médicos y de enfermería asignado', null=True),
        ),
        migrations.AddField(
            model_name='cuna',
            name='temperatura',
            field=models.FloatField(blank=True, help_text='Temperatura corporal en grados Celsius (°C)', null=True),
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ritmo_cardiaco', 'Frecuencia Cardíaca'), ('spo2', 'Saturación de Oxígeno (SPO2)'), ('temperatura', 'Temperatura'), ('canula', 'Desconexión de Cánula'), ('otra', 'Otra Alerta')], default='otra', help_text='Tipo de signo vital o sensor comprometido', max_length=30)),
                ('mensaje', models.CharField(help_text='Descripción o mensaje detallado de la alerta', max_length=255)),
                ('nivel', models.CharField(choices=[('Info', 'Información'), ('Advertencia', 'Advertencia'), ('Critica', 'Crítica')], default='Info', help_text='Severidad de la alerta', max_length=20)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se generó la alerta')),
                ('paciente', models.ForeignKey(help_text='Bebé al que pertenece la alerta', on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='cunas.bebe')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
            },
        ),
    ]
