# Generated by Django 6.1 on 2026-09-07 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cunas", "0004_bebe_diagnostico_bebe_fecha_ingreso_and_more"),
        ("cunas", "0004_plancuidado"),
    ]

    operations = []
