# Generated by Django 6.1 on 2026-09-23 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunas', '0005_merge_20260907_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='activa',
            field=models.BooleanField(default=True, help_text='Indica si la alerta está actualmente activa o ya fue resuelta'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='cuna',
            field=models.ForeignKey(blank=True, help_text='Cuna donde ocurrió el evento de alerta', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='cunas.cuna'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='valor_leido',
            field=models.FloatField(blank=True, help_text='Valor numérico del signo vital al momento de la alerta', null=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='paciente',
            field=models.ForeignKey(blank=True, help_text='Bebé al que pertenece la alerta', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='cunas.bebe'),
        ),
    ]
