# Generated by Django 6.1 on 2026-09-15 16:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunas', '0005_merge_20260907_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificador del turno (ej: Mañana, Tarde, Noche)', max_length=50, unique=True)),
                ('hora_inicio', models.TimeField(blank=True, help_text='Hora de inicio programada del turno', null=True)),
                ('hora_fin', models.TimeField(blank=True, help_text='Hora de término programada del turno', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el turno está habilitado operativamente')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.AddField(
            model_name='bebe',
            name='matriculado',
            field=models.BooleanField(default=True, help_text='Indica si el bebé está matriculado y activo en la institución'),
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombre completo del apoderado o tutor legal', max_length=150)),
                ('rut', models.CharField(help_text='RUT o identificador único del apoderado (ej: 12.345.678-9)', max_length=12, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico de contacto', max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, help_text='Número telefónico de contacto', max_length=30, null=True)),
                ('bebe', models.ForeignKey(help_text='Bebé asociado del cual es apoderado o tutor', on_delete=django.db.models.deletion.CASCADE, related_name='apoderados', to='cunas.bebe')),
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
            },
        ),
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha de la asignación del turno')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la asignación está actualmente en vigencia')),
                ('cunas', models.ManyToManyField(blank=True, help_text='Subconjunto de cunas asignadas bajo su responsabilidad en este turno', related_name='asignaciones_turno', to='cunas.cuna')),
                ('medico', models.ForeignKey(help_text='Profesional de salud a cargo del turno', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_turno', to='cunas.medico')),
                ('turno', models.ForeignKey(help_text='Turno asignado (ej: Mañana, Tarde, Noche)', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='cunas.turno')),
            ],
            options={
                'verbose_name': 'Asignación de Turno',
                'verbose_name_plural': 'Asignaciones de Turno',
            },
        ),
    ]
