# Generated by Django 6.1 on 2026-09-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunas', '0005_merge_20260907_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebe',
            name='matriculado_activo',
            field=models.BooleanField(default=True, help_text='Indica si el niño está matriculado activamente (requerido para vista de apoderados)'),
        ),
        migrations.CreateModel(
            name='Educadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Ej: Ana Gómez', max_length=150)),
                ('turno', models.CharField(help_text='Turno rotativo (ej: Mañana, Tarde, Noche)', max_length=50)),
                ('cunas_asignadas', models.ManyToManyField(blank=True, help_text='Subconjunto de cunas bajo su responsabilidad en este turno', related_name='educadoras_turno', to='cunas.cuna')),
            ],
            options={
                'verbose_name': 'Educadora',
                'verbose_name_plural': 'Educadoras',
            },
        ),
    ]
