# Generated by Django 6.1 on 2026-09-30 13:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunas', '0006_alerta_activa_alerta_cuna_alerta_valor_leido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebe',
            name='edad_gestacional',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Edad gestacional en semanas', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bebe',
            name='identificador',
            field=models.CharField(blank=True, help_text='Identificador único del paciente, ej: BEB-0001', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bebe',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bebe',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bebe',
            name='edad_meses',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bebe',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bebe',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bebe',
            name='medico_a_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='cunas.medico'),
        ),
        migrations.AlterField(
            model_name='bebe',
            name='nombre_completo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bebe',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bebe',
            name='plan_cuidados',
            field=models.TextField(blank=True, null=True),
        ),
    ]
