# Generated by Django 6.1 on 2026-09-23 13:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunas', '0006_alerta_activa_alerta_cuna_alerta_valor_leido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialSignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ritmo_cardiaco', models.IntegerField(blank=True, help_text='Frecuencia cardíaca en latidos por minuto (bpm)', null=True)),
                ('spo2', models.IntegerField(blank=True, help_text='Saturación de oxígeno en sangre (%)', null=True)),
                ('temperatura', models.FloatField(blank=True, help_text='Temperatura corporal en grados Celsius (°C)', null=True)),
                ('fecha_hora', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Fecha y hora de la lectura de telemetría')),
                ('cuna', models.ForeignKey(help_text='Cuna a la que corresponde la lectura', on_delete=django.db.models.deletion.CASCADE, related_name='historial_signos', to='cunas.cuna')),
            ],
            options={
                'verbose_name': 'Historial de Signo Vital',
                'verbose_name_plural': 'Historial de Signos Vitales',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
